# Based on https://github.com/mvdan/github-actions-golang
on: [push, pull_request, workflow_dispatch]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: cargo test
